<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>svg_Expand</name>
   <tag></tag>
   <elementGuidId>b1cefec7-b9b7-4a31-885f-1972d1458c0a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>svg.kadence-svg-icon.kadence-arrow-down-svg</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='Home'])[1]/following::*[name()='svg'][1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>svg</value>
      <webElementGuid>b7036be2-14c5-4d03-818d-a478c7d71315</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>a75f7a42-516a-41f9-a676-8d8bf43afc90</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>kadence-svg-icon kadence-arrow-down-svg</value>
      <webElementGuid>9e9e2c68-610a-4a46-a348-b33f2664426b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>fill</name>
      <type>Main</type>
      <value>currentColor</value>
      <webElementGuid>9407c4ce-3a9a-4f19-9569-12d32c71419d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>version</name>
      <type>Main</type>
      <value>1.1</value>
      <webElementGuid>49753f87-dfe9-48a1-a9a8-86b414447575</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xmlns</name>
      <type>Main</type>
      <value>http://www.w3.org/2000/svg</value>
      <webElementGuid>e26fdc4d-6306-4637-8970-dd67021e8084</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>24</value>
      <webElementGuid>22cd4168-fc53-4fc0-9485-e9d9434558af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>24</value>
      <webElementGuid>22d78b3c-4066-42ae-a342-a43836dd7128</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>viewBox</name>
      <type>Main</type>
      <value>0 0 24 24</value>
      <webElementGuid>8b1c11cd-2c9c-4fcb-a492-e78a4d54b967</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Expand
				</value>
      <webElementGuid>0f0caef7-e019-4b17-900f-aab8c8bdeee7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;menu-item-3173&quot;)/a[1]/span[@class=&quot;nav-drop-title-wrap&quot;]/span[@class=&quot;dropdown-nav-toggle&quot;]/span[@class=&quot;kadence-svg-iconset svg-baseline&quot;]/svg[@class=&quot;kadence-svg-icon kadence-arrow-down-svg&quot;]</value>
      <webElementGuid>574c4651-1053-4380-94b4-6e32850fab67</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Home'])[1]/following::*[name()='svg'][1]</value>
      <webElementGuid>d6d8ef26-9ac2-4b36-a6bb-7742c28b68f8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Agile Testing'])[1]/preceding::*[name()='svg'][1]</value>
      <webElementGuid>6538eb50-dffd-4c6f-9c40-faa93fcdc520</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='JUnit'])[1]/preceding::*[name()='svg'][1]</value>
      <webElementGuid>c5c4d5d9-4023-421c-b5d0-d77720f25afa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//svg[(text() = 'Expand
				' or . = 'Expand
				')]</value>
      <webElementGuid>9183f746-38d0-4a3b-a333-5c95d580d543</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
