<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Login</name>
   <tag></tag>
   <elementGuidId>16b993e5-e2f5-4529-9b33-b2eded5969d9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='postForm']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#postForm</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>d77beac8-56c2-4142-bcda-67c2222574c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>postForm</value>
      <webElementGuid>dad827d0-3dc2-4d02-8920-6b5b9eecb983</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>sendLogin(document.getElementById(&quot;username&quot;).value, document.getElementById(&quot;password&quot;).value)</value>
      <webElementGuid>cbc334cd-b41a-4162-bc5a-ba8a8e0a80b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Login</value>
      <webElementGuid>8bc6afad-2835-494b-bfa9-99a38ff43acf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;postForm&quot;)</value>
      <webElementGuid>4fa9d94f-0e51-4abd-94be-54e29601bbb4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='postForm']</value>
      <webElementGuid>3b9a3d39-dd54-4e4e-bf98-d97a43821776</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='login_form']/div[3]/button</value>
      <webElementGuid>56d8c6b2-a46e-4ba8-9dc4-185a1ccf4260</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Password *'])[1]/following::button[1]</value>
      <webElementGuid>91edcef3-b7e2-477e-842a-acda2f525582</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Username *'])[1]/following::button[1]</value>
      <webElementGuid>3b3745ea-9537-4412-88ae-5c505ef276ac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Faysal Bank Limited Password Assistance'])[1]/preceding::button[1]</value>
      <webElementGuid>09c256d6-1391-48ac-b3b1-f09b929aa49b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button</value>
      <webElementGuid>45e464c8-5447-4805-83aa-1a8389c4eae2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'postForm' and (text() = 'Login' or . = 'Login')]</value>
      <webElementGuid>e48ae1cb-19f8-4c02-9c4d-ca6eac9f009e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
