<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Client IndicatorBasis for offering diff_06cc81</name>
   <tag></tag>
   <elementGuidId>763bf526-95a4-417c-be08-1ea80418da0e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>mat-form-field.mat-form-field.ng-tns-c1-138.mat-primary.mat-form-field-type-mat-select.mat-form-field-appearance-standard.mat-form-field-can-float.mat-form-field-has-label.mat-form-field-hide-placeholder.ng-untouched.ng-pristine.ng-invalid > div.mat-form-field-wrapper > div.mat-form-field-flex > div.mat-form-field-infix</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='ui-tabpanel-0']/dynamic-form/form/div/form-select[3]/div/mat-form-field/div/div/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>fb140b2a-3d8d-46c5-a33c-66f3b8163f6a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-form-field-infix</value>
      <webElementGuid>c310af65-6a17-4ea4-9129-dde571a30a04</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Client IndicatorBasis for offering differentiated treatment to the customer.Client Indicator *</value>
      <webElementGuid>a23b25d1-721c-4ea9-b8f4-413853ba6f73</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ui-tabpanel-0&quot;)/dynamic-form[1]/form[@class=&quot;dynamic-form md-inline-form ng-invalid ng-touched ng-dirty&quot;]/div[@class=&quot;four-col&quot;]/form-select[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;dynamic-field form-select ng-invalid ng-touched ng-dirty&quot;]/mat-form-field[@class=&quot;mat-form-field ng-tns-c1-138 mat-primary mat-form-field-type-mat-select mat-form-field-appearance-standard mat-form-field-can-float mat-form-field-has-label mat-form-field-hide-placeholder ng-untouched ng-pristine ng-invalid&quot;]/div[@class=&quot;mat-form-field-wrapper&quot;]/div[@class=&quot;mat-form-field-flex&quot;]/div[@class=&quot;mat-form-field-infix&quot;]</value>
      <webElementGuid>4c1cbe93-baf1-45e5-a6d7-44828c628887</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ui-tabpanel-0']/dynamic-form/form/div/form-select[3]/div/mat-form-field/div/div/div</value>
      <webElementGuid>f198e32e-baff-4eb5-82df-3381268c6db4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Category Type'])[1]/following::div[8]</value>
      <webElementGuid>0f53557e-8c5e-4070-a9de-92eec10b4c09</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Identifies the type of details to be captured for the customer.'])[1]/following::div[8]</value>
      <webElementGuid>97de358c-c767-4e68-bc83-5638ca653185</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form-select[3]/div/mat-form-field/div/div/div</value>
      <webElementGuid>03cb370c-5935-4caf-84ef-1daa68286c0e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Client IndicatorBasis for offering differentiated treatment to the customer.Client Indicator *' or . = 'Client IndicatorBasis for offering differentiated treatment to the customer.Client Indicator *')]</value>
      <webElementGuid>8373ff0b-5023-4721-8212-fad0543f5941</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
