<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>mat-icon_Country of Residence_fa fa-search _bed379</name>
   <tag></tag>
   <elementGuidId>e025a5b6-c3aa-44fa-94cd-c0f875248de5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.mat-icon-button.ng-star-inserted.cdk-focused.cdk-mouse-focused > span.mat-button-wrapper > mat-icon.fa.fa-search.mat-icon.notranslate.material-icons.mat-icon-no-color</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='ui-tabpanel-0']/dynamic-form/form/div/form-lov[2]/div/mat-form-field/div/div/div[2]/button/span/mat-icon</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>mat-icon</value>
      <webElementGuid>14c00f39-214c-42ec-b679-4f8da84e9550</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fa fa-search mat-icon notranslate material-icons mat-icon-no-color</value>
      <webElementGuid>fe795621-ef04-4452-bdf9-d35f1e72c3cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>bb9789ee-4fe2-4f8a-8740-fb4cff87796d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>0a172720-d1aa-4407-92ac-be30618650f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ui-tabpanel-0&quot;)/dynamic-form[1]/form[@class=&quot;dynamic-form md-inline-form ng-touched ng-dirty ng-valid&quot;]/div[@class=&quot;four-col&quot;]/form-lov[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;dynamic-field form-lov ng-touched ng-dirty ng-valid&quot;]/mat-form-field[@class=&quot;mat-form-field ng-tns-c1-144 mat-primary mat-form-field-type-mat-input mat-form-field-appearance-standard mat-form-field-can-float mat-form-field-has-label ng-untouched ng-pristine mat-form-field-should-float ng-valid&quot;]/div[@class=&quot;mat-form-field-wrapper&quot;]/div[@class=&quot;mat-form-field-flex&quot;]/div[@class=&quot;mat-form-field-suffix ng-tns-c1-144 ng-star-inserted&quot;]/button[@class=&quot;mat-icon-button ng-star-inserted cdk-focused cdk-mouse-focused&quot;]/span[@class=&quot;mat-button-wrapper&quot;]/mat-icon[@class=&quot;fa fa-search mat-icon notranslate material-icons mat-icon-no-color&quot;]</value>
      <webElementGuid>90d0d6d0-003e-4f63-81db-d96b439970bc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ui-tabpanel-0']/dynamic-form/form/div/form-lov[2]/div/mat-form-field/div/div/div[2]/button/span/mat-icon</value>
      <webElementGuid>4fcaaeb2-dc55-4fc0-91a9-cddba90e7ad8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form-lov[2]/div/mat-form-field/div/div/div[2]/button/span/mat-icon</value>
      <webElementGuid>64095134-0671-4f16-8256-20984750f516</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
