<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>mat-card-content_Customer Type  Description_781eeb</name>
   <tag></tag>
   <elementGuidId>41a8f24b-2cf8-4d70-9759-41b68870ba27</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>cbs-query-list > mat-card.mat-card > mat-card-content.mat-card-content</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//mat-dialog-container[@id='mat-dialog-2']/cbs-lov-dialog/mat-dialog-content/cbs-query-list/mat-card/mat-card-content</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>mat-card-content</value>
      <webElementGuid>3cc48280-a7bc-4203-afbe-00910daa72cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-card-content</value>
      <webElementGuid>b9bd69ed-1b2c-4ce2-961d-4af3c25c3cd3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Customer Type  Description  COR  CORPORATE CLIENT  EMP  EMPLOYEE  GEN  General Client type  GOV  GOVERNMENT  IND  Individual  NBK  Non Bank  QAC  Testing  SLP  Sole Proprietor navigate_beforenavigate_next</value>
      <webElementGuid>c8ba1b09-a118-4d98-8115-f9c9a9304d9d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mat-dialog-2&quot;)/cbs-lov-dialog[@class=&quot;ng-star-inserted&quot;]/mat-dialog-content[@class=&quot;mat-dialog-content&quot;]/cbs-query-list[1]/mat-card[@class=&quot;mat-card&quot;]/mat-card-content[@class=&quot;mat-card-content&quot;]</value>
      <webElementGuid>8d54fe8d-91f8-4e67-893b-50ea2b6b0dc9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//mat-dialog-container[@id='mat-dialog-2']/cbs-lov-dialog/mat-dialog-content/cbs-query-list/mat-card/mat-card-content</value>
      <webElementGuid>b83383e2-743f-46c9-b18c-05a4a0875b48</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select Filter:'])[2]/following::mat-card-content[1]</value>
      <webElementGuid>823bd233-27ef-43c8-95a1-ac13449ccf09</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select Filter:'])[1]/following::mat-card-content[1]</value>
      <webElementGuid>b9b9f3f0-0d97-429f-9931-14d2777f2271</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//cbs-query-list/mat-card/mat-card-content</value>
      <webElementGuid>9423eb78-7c0f-4e46-8db5-1e972899afe7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//mat-card-content[(text() = ' Customer Type  Description  COR  CORPORATE CLIENT  EMP  EMPLOYEE  GEN  General Client type  GOV  GOVERNMENT  IND  Individual  NBK  Non Bank  QAC  Testing  SLP  Sole Proprietor navigate_beforenavigate_next' or . = ' Customer Type  Description  COR  CORPORATE CLIENT  EMP  EMPLOYEE  GEN  General Client type  GOV  GOVERNMENT  IND  Individual  NBK  Non Bank  QAC  Testing  SLP  Sole Proprietor navigate_beforenavigate_next')]</value>
      <webElementGuid>2e811c40-0b76-420e-a2d0-0199593a8139</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
